doctrine:
    dbal:
        
        url: 'mysql://root@127.0.0.1:3306/laboratoirecovid?serverVersion=5.7'
        
        # url: 'mysql://dbu698110:9h5mkanIi***77@db5003499644.hosting-data.io:3306/dbs2844357'
        # url: 'mysql://root:@127.0.0.1:3306/eleve'
        # url: 'mysql://dbu726646:9h5mkanIi@77@db5002402952.hosting-data.io:3306/dbs1921440'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        # la valeur de url doit être changée en production par le host de base de donnée en production
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

